## Objetivo: a partir de los datos de ventas de libros proyectar las ventas del proximo mes

In [1]:
# Importo las librerias

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
#Cargo el dataset

df = pd.read_excel("Data/data.xlsx",  skiprows = 1,usecols = 'C:AU')

In [29]:
df

,TITLE,AUTHOR,LABEL,DIVISION,LAUCNCH DATE,SEGMENT,TYPE,PVP,Ener,Feb,...,Abr.2,May.2,Jun.2,Jul.2,Agos.2,Sept.2,Oct.2,Nov.2,Dic.2,Ener.3
0,Libro 1,Autor 1,GRJ-020,COMERCIAL,1999-01-01,AUTOAYUDA Y SUPERACIÓN,FONDO,259,17.0,9.0,...,18,19,73,194,107,121,101,106,241,120
1,Libro 2,Autor 2,AGL-021,COMERCIAL,2009-11-01,AUTOAYUDA,FONDO,239,13.0,18.0,...,5,0,11,12,13,16,14,8,30,11
2,Libro 3,Autor 3,ALF-022,LITERARIA,2010-09-01,BIBLIOTECA SARAMAGO,FONDO,329,133.0,122.0,...,31,9,31,88,50,71,87,61,111,33
3,Libro 4,Autor 4,DEB-023,BOLSILLO,2011-05-01,CONTEMPORÁNEA,FONDO,209,161.0,115.0,...,43,43,76,142,106,91,67,67,153,56
4,Libro 5,Autor 5,DEB-023,BOLSILLO,2011-05-01,CONTEMPORÁNEA,FONDO,209,68.0,86.0,...,34,73,71,99,82,77,64,69,125,71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
651,Libro 653,Autor 653,ALFJ-025,INFANTIL Y JUVENIL,2018-12-01,FICCIÓN JUVENIL,FONDO,309,0.0,0.0,...,0,0,1,2,2,4,0,2,2,2
652,Libro 654,Autor 654,ALFI-031,INFANTIL Y JUVENIL,2018-12-01,MIDDLE GRADE,FONDO,199,0.0,0.0,...,0,1,2,2,1,5,1,4,2,3
653,Libro 655,Autor 655,LUM-030,LITERARIA,2018-12-01,LUMEN,FONDO,289,0.0,0.0,...,12,7,22,12,15,26,61,71,136,48
654,Libro 656,Autor 656,ROCI-028,INFANTIL Y JUVENIL,2018-12-01,JUVENIL,FONDO,249,0.0,0.0,...,6,1,5,10,5,5,5,7,30,11
655,Libro 657,Autor 657,LIT-034,LITERARIA,2018-12-01,CABALLO DE TROYA,FONDO,339,0.0,0.0,...,0,0,1,0,2,2,1,3,1,3

In [30]:
#Creo un vector de secuencia de fechas mensuales

import datetime

#Vector de meses
meses = pd.date_range('1/1/2018', periods = 37, freq ='M').strftime("%Y-%m-%d").tolist()

#Nombre del resto de las columnas
columnas = ['TITLE','AUTHOR','LABEL','DIVISION','LAUCNCH DATE','SEGMENT','TYPE','PVP']

#Concateno las listas
labels = np.concatenate([columnas,meses])

#Renombro el data frame
df.columns = labels

df.head()

,TITLE,AUTHOR,LABEL,DIVISION,LAUCNCH DATE,SEGMENT,TYPE,PVP,2018-01-31,2018-02-28,...,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31
0,Libro 1,Autor 1,GRJ-020,COMERCIAL,1999-01-01,AUTOAYUDA Y SUPERACIÓN,FONDO,259,17.0,9.0,...,18,19,73,194,107,121,101,106,241,120
1,Libro 2,Autor 2,AGL-021,COMERCIAL,2009-11-01,AUTOAYUDA,FONDO,239,13.0,18.0,...,5,0,11,12,13,16,14,8,30,11
2,Libro 3,Autor 3,ALF-022,LITERARIA,2010-09-01,BIBLIOTECA SARAMAGO,FONDO,329,133.0,122.0,...,31,9,31,88,50,71,87,61,111,33
3,Libro 4,Autor 4,DEB-023,BOLSILLO,2011-05-01,CONTEMPORÁNEA,FONDO,209,161.0,115.0,...,43,43,76,142,106,91,67,67,153,56
4,Libro 5,Autor 5,DEB-023,BOLSILLO,2011-05-01,CONTEMPORÁNEA,FONDO,209,68.0,86.0,...,34,73,71,99,82,77,64,69,125,71

In [31]:
#hago un melt con el data frame

df = df.melt(id_vars= columnas, var_name= "Mes",value_name= "Cantidad")

df

,TITLE,AUTHOR,LABEL,DIVISION,LAUCNCH DATE,SEGMENT,TYPE,PVP,Mes,Cantidad
0,Libro 1,Autor 1,GRJ-020,COMERCIAL,1999-01-01,AUTOAYUDA Y SUPERACIÓN,FONDO,259,2018-01-31,17.0
1,Libro 2,Autor 2,AGL-021,COMERCIAL,2009-11-01,AUTOAYUDA,FONDO,239,2018-01-31,13.0
2,Libro 3,Autor 3,ALF-022,LITERARIA,2010-09-01,BIBLIOTECA SARAMAGO,FONDO,329,2018-01-31,133.0
3,Libro 4,Autor 4,DEB-023,BOLSILLO,2011-05-01,CONTEMPORÁNEA,FONDO,209,2018-01-31,161.0
4,Libro 5,Autor 5,DEB-023,BOLSILLO,2011-05-01,CONTEMPORÁNEA,FONDO,209,2018-01-31,68.0
...,...,...,...,...,...,...,...,...,...,...
24267,Libro 653,Autor 653,ALFJ-025,INFANTIL Y JUVENIL,2018-12-01,FICCIÓN JUVENIL,FONDO,309,2021-01-31,2.0
24268,Libro 654,Autor 654,ALFI-031,INFANTIL Y JUVENIL,2018-12-01,MIDDLE GRADE,FONDO,199,2021-01-31,3.0
24269,Libro 655,Autor 655,LUM-030,LITERARIA,2018-12-01,LUMEN,FONDO,289,2021-01-31,48.0
24270,Libro 656,Autor 656,ROCI-028,INFANTIL Y JUVENIL,2018-12-01,JUVENIL,FONDO,249,2021-01-31,11.0
24271,Libro 657,Autor 657,LIT-034,LITERARIA,2018-12-01,CABALLO DE TROYA,FONDO,339,2021-01-31,3.0

In [42]:
df['Mes'] = pd.to_datetime(df['Mes'])



df['Cantidad'] = df['Cantidad'].fillna(0)

df.isnull().sum()

TITLE           0
AUTHOR          0
LABEL           0
DIVISION        0
LAUCNCH DATE    0
SEGMENT         0
TYPE            0
PVP             0
Mes             0
Cantidad        0
dtype: int64